// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO0CRchYhC-KMPT-0bt4sOF01oI9yEnBk',
    appId: '1:677225758780:web:adaea96c83ccc0ab798339',
    messagingSenderId: '677225758780',
    projectId: 'meu-personal-922ee',
    authDomain: 'meu-personal-922ee.firebaseapp.com',
    storageBucket: 'meu-personal-922ee.firebasestorage.app',
    measurementId: 'G-V6C7CFP7XH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBalH5-KkkjMSovaZ-PmmoL5N3RNnF2afQ',
    appId: '1:677225758780:android:255d80bda79a340d798339',
    messagingSenderId: '677225758780',
    projectId: 'meu-personal-922ee',
    storageBucket: 'meu-personal-922ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz2njaLU9f33GzN7y1_FsnQI_VhtD20UI',
    appId: '1:677225758780:ios:7505cd39e2dc3279798339',
    messagingSenderId: '677225758780',
    projectId: 'meu-personal-922ee',
    storageBucket: 'meu-personal-922ee.firebasestorage.app',
    iosBundleId: 'com.example.tcc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz2njaLU9f33GzN7y1_FsnQI_VhtD20UI',
    appId: '1:677225758780:ios:7505cd39e2dc3279798339',
    messagingSenderId: '677225758780',
    projectId: 'meu-personal-922ee',
    storageBucket: 'meu-personal-922ee.firebasestorage.app',
    iosBundleId: 'com.example.tcc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO0CRchYhC-KMPT-0bt4sOF01oI9yEnBk',
    appId: '1:677225758780:web:ceecac03edf48a41798339',
    messagingSenderId: '677225758780',
    projectId: 'meu-personal-922ee',
    authDomain: 'meu-personal-922ee.firebaseapp.com',
    storageBucket: 'meu-personal-922ee.firebasestorage.app',
    measurementId: 'G-YRXJ3JB045',
  );

}